package com.lwons.assist.action

enum class AssistAction {
    ACTION_HOME,
    ACTION_SETTINGS,
    ACTION_SCREENSHOT,
    ACTION_SILENT,
    ACTION_LOCK,
    ACTION_VOLUME_UP,
    ACTION_VOLUME_DOWN,
    ACTION_ROTATION,
    ACTION_BLUETOOTH,
    ACTION_WIFI,
    ACTION_FLASHLIGHT,
    ACTION_CAMERA,
    ACTION_CALCULATOR,
    ACTION_DARK_MODE,
    ACTION_BRIGHTNESS,
    ACTION_RECORD,
}